# Compose tshark elasticsearch experiment factory
version: '2'
services:

   # ELASTICSEARCH cluster
  es1:
    container_name: es1
    image: danielguerra/alpine-elasticsearch:5.2.2-cluster
    hostname: es1
    environment:
      - CLUSTER_NAME=tshark-cluster
      - network.host=es1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es2:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  es2:
    container_name: es2
    image: danielguerra/alpine-elasticsearch:5.2.2-cluster
    hostname: es2
    links:
     - es1:es1
    environment:
      - NODE_MASTER=false
      - CLUSTER_NAME=tshark-cluster
      - UNICAST_HOSTS=es1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

  # KIBANA to view our data
  kibana:
    container_name: kibana
    image: danielguerra/alpine-kibana:5.2.1
    hostname: kibana
    links:
     - es1:elasticsearch
    ports:
     - 5601:5601
    networks:
      - esnet

  # TSHARK
  tshark:
    container_name: tshark
    image: danielguerra/tshark-elasticsearch
    hostname: tshark
    tty: true
    links:
     - es1:elasticsearch
    volumes:
     - pcap:/data/pcap
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  pcap:
    driver: local

networks:
  esnet:
    driver: bridge
